apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - upstream

patches:
  - mutatingwebhooks.yaml
  - controller.yaml

generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
- name: mutatingwebhook
  namespace: topolvm-system
  type: "Opaque"
  files:
  - ca.crt=./build/certs/ca.pem
  - tls.crt=./build/certs/server.pem
  - tls.key=./build/certs/server-key.pem

configurations:
  - params.yaml
vars:
  - name: TLSCERT
    objref:
      kind: Secret
      version: v1
      name: mutatingwebhook
    fieldref:
      fieldpath: data[ca.crt]
